### ISSUE TITLE
Design update

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/532_Group_22#79]
- [x] Add app description on sidebar
- [x] Peer feedback #67 You can also add more white space between filters.
- [x] TA feedback #66 Nice touch adding a graph save option. It would be helpful if you made a note to let the user know they can do this. It was hard to notice.
- [x] Peer feedback #67 Would be great if you add a side note to explain what the empty plots mean based on user selections (e.g. no data).
- [x] Peer feedback #67 : the font of the two tabs could be bigger & bolded.
